SELECT 
    f."Game_Facts_ID",
	d."Date",
	t."Team",
 	o."Opponent",
	f."TOI",
	f."CF", 
	f."CA",
	f."CF%", 
	f."FF", 
	f."FA",
	f."FF%", 
	f."SF", 
	f."SA", 
	f."SF%", 
	f."GF", 
	f."GA",
	f."GF%", 
	f."xGF",
	f."xGA",
	f."xGF%", 
	f."SCF",
	f."SCA", 
	f."SCF%",
	f."HDCF",
	f."HDCA",
	f."HDCF%", 
	f."HDSF",
	f."HDSA", 
	f."HDSF%", 
	f."HDGF", 
	f."HDGA", 
	f."HDGF%",
	f."HDSH%",
	f."HDSV%",
	f."MDCF",
	f."MDCA", 
	f."MDCF%",
	f."MDSF", 
	f."MDSA", 
	f."MDSF%", 
	f."MDGF",
	f."MDGA",
	f."MDGF%", 
	f."MDSH%",
	f."MDSV%", 
	f."LDCF", 
	f."LDCA", 
	f."LDCF%", 
	f."LDSF",
	f."LDSA",
	f."LDSF%",
	f."LDGF", 
	f."LDGA",
	f."LDGF%",
	f."LDSH%",
	f."LDSV%",
	f."SH%",
	f."SV%", 
	f."PDO",
	f."Attendance"
FROM {{ ref('raw_game_facts') }} AS f LEFT JOIN {{ ref('raw_dates') }} AS d
ON f."Date_ID" = d."Date_ID"
LEFT JOIN {{ ref('raw_teams') }} AS t
ON f."Team_ID" = t."Team_ID"
LEFT JOIN {{ ref('raw_opponents') }} AS o
ON f."Opponent_ID" = o."Opponent_ID"
